global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.201:9100', '192.168.100.202:9100']

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.202:9323']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.100.203:9090']